apiVersion: v1

kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: influxdb
  INFLUXDB_URL: http://influxdb-service:8086
  INFLUXDB_USER: influxdb
  INFLUXDB_USER_PASSWORD: influxdb
---
apiVersion: v1

kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [[outputs.influxdb]]
      urls = ["http://influxdb-service:8086"]
      database = "puffigialli"
      skip_database_creation = false
      username = "influxdb"
      password = "influxdb"
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "20s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
      # Read metrics about cpu usage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: true
          envFrom:
            - secretRef:
                name: telegraf-secrets
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: allow
  name: telegraf-service
  labels:
    app: telegraf
spec:
  type: ClusterIP
  ports:
    - name: telegraf
      port: 8125
      protocol: TCP
      targetPort: 8125
  selector:
    app: telegraf

