apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: allow
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
#  loadBalancerIP: MINI192.168.65.3  #아이피 주소 잡아줌.
  ports:
    - port: 5050
      name: http
      targetPort: 80
      protocol: TCP
